import assert from "node:assert/strict";
import test from "node:test";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { HermesAgentExecutor } from "../src/adapters/hermes-agent-executor.js";
import { ensureWorkspace } from "../src/adapters/git-workspace.js";

const wp = { executionId: "exec-1", taskId: "task-1", workPackageId: "wp-1", title: "hostile\n title", acceptanceCriteria: [{ id: "c1", text: "line\n--body" }], repository: { identity: "repo" } };
const git = (cwd, args) => execFileSync("git", args, { cwd, encoding: "utf8" }).trim();
const ctx = (r, branch = r.branch) => ({ workspace: { path: r.workspace, baseSha: r.baseSha, branch } });
function repo() { const root = mkdtempSync(join(tmpdir(), "hermes-")); git(root, ["init", "-q", "-b", "main"]); git(root, ["config", "user.email", "author@example.test"]); git(root, ["config", "user.name", "Author"]); writeFileSync(join(root, "base"), "base\n"); git(root, ["add", "."]); git(root, ["commit", "-qm", "base"]); const baseSha = git(root, ["rev-parse", "HEAD"]); const branch = "loop/task-1/exec-1"; const workspace = ensureWorkspace({ repoPath: root, workspacesDir: join(root, "workspaces"), executionId: "exec-1", taskId: "task-1", baseSha, branch }).path; return { root, workspace, baseSha, branch }; }
const done = async (args) => args.includes("create") ? { stdout: JSON.stringify({ id: "h-1" }) } : { stdout: JSON.stringify({ status: "done" }) };
function commit(r, trailer = true, dirty = false) { writeFileSync(join(r.workspace, "impl"), "ok\n"); git(r.workspace, ["add", "."]); git(r.workspace, ["commit", "-qm", `impl${trailer ? `\n\nLoop-Execution-Id: ${wp.executionId}\nLoop-Task-Id: ${wp.taskId}` : ""}`]); if (dirty) writeFileSync(join(r.workspace, "dirty"), "x"); }

test("owned committed implementation returns Git facts", async () => { const r = repo(); commit(r); const got = await new HermesAgentExecutor({ pollMs: 0, run: done }).execute(wp, ctx(r)); assert.equal(got.head, git(r.workspace, ["rev-parse", "HEAD"])); assert.equal(got.base, r.baseSha); assert.equal(got.branch, r.branch); assert.equal(got.authorId, "author@example.test"); assert.deepEqual(got.changedFiles, ["impl"]); });
for (const [name, action] of [["foreign commit", r => commit(r, false)], ["wrong branch", r => commit(r)], ["marker mismatch", r => { commit(r); const p = join(git(r.workspace, ["rev-parse", "--git-dir"]), "loop-execution.json"); const m = JSON.parse(readFileSync(p)); m.executionId = "other"; writeFileSync(p, JSON.stringify(m)); }], ["committed and dirty", r => commit(r, true, true)]]) test(`${name} is rejected`, async () => { const r = repo(); action(r); const branch = name === "wrong branch" ? "wrong" : r.branch; await assert.rejects(new HermesAgentExecutor({ pollMs: 0, run: done }).execute(wp, ctx(r, branch)), e => e.code === "HERMES_GIT_INCOMPLETE"); });
test("done without commit is rejected", async () => { const r = repo(); await assert.rejects(new HermesAgentExecutor({ pollMs: 0, run: done }).execute(wp, ctx(r)), /without an owned clean/); });
test("resume preserves uncommitted work", async () => { const r = repo(); writeFileSync(join(r.workspace, "keep"), "keep"); await assert.rejects(new HermesAgentExecutor({ pollMs: 0, run: done }).resume(wp, ctx(r))); assert.equal(readFileSync(join(r.workspace, "keep"), "utf8"), "keep"); });

test("CLI contract uses exact workspace, body-file, trailers and distinct stable keys", async () => { const calls = []; const bodies = []; const run = async args => { calls.push(args); if (args.includes("--body-file")) bodies.push(readFileSync(args[args.indexOf("--body-file") + 1], "utf8")); return args.includes("create") ? { stdout: JSON.stringify({ id: "x" }) } : { stdout: JSON.stringify({ status: "blocked" }) }; }; const e = new HermesAgentExecutor({ board: "b", pollMs: 0, run }); await assert.rejects(e.execute(wp, { workspace: { path: "/exact/worktree", baseSha: "a".repeat(40), branch: "b" } }), x => x.code === "HERMES_BLOCKED"); const a = calls[0]; assert.deepEqual(a.slice(0, 3), ["kanban", "--board", "b"]); assert.ok(a.includes("dir:/exact/worktree")); assert.ok(a.includes("--body-file")); assert.ok(!a.includes("--body")); assert.equal(a[a.indexOf("--idempotency-key") + 1], "loop-exec-1-execute"); const body = bodies[0]; assert.match(body, /Loop-Execution-Id: exec-1/); assert.match(body, /Loop-Task-Id: task-1/); assert.match(body, /line\n--body/); assert.notEqual(e.idempotencyKey(wp, false), e.idempotencyKey(wp, true)); });
test("resume body preserves multiline hostile Unicode text and has stable resume key", async () => { const calls = []; const bodies = []; const hostile = { ...wp, title: "multi\n--flag $HOME 'quote' ☃", acceptanceCriteria: [{ id: "x", text: "line\n--flag; rm 'x' ☃" }] }; const e = new HermesAgentExecutor({ pollMs: 0, run: async args => { calls.push(args); if (args.includes("--body-file")) bodies.push(readFileSync(args[args.indexOf("--body-file") + 1], "utf8")); return args.includes("create") ? { stdout: JSON.stringify({ id: "x" }) } : { stdout: JSON.stringify({ status: "blocked" }) }; } }); await assert.rejects(e.resume(hostile, { workspace: { path: "/exact", baseSha: "b".repeat(40), branch: "b" } })); const a = calls[0]; assert.equal(a[a.indexOf("--idempotency-key") + 1], "loop-exec-1-resume"); const body = bodies[0]; assert.match(body, /multi\n--flag \$HOME 'quote' ☃/); assert.match(body, /line\n--flag; rm 'x' ☃/); });
for (const [label, out, code, cls, retry] of [["unknown", JSON.stringify({ status: "mystery" }), "HERMES_UNKNOWN_STATUS", "TASK_FAILURE", false], ["malformed", "not-json", "HERMES_MALFORMED_OUTPUT", "TASK_FAILURE", false], ["blocked", JSON.stringify({ status: "blocked" }), "HERMES_BLOCKED", "TASK_FAILURE", false]]) test(`${label} fails closed`, async () => { const e = new HermesAgentExecutor({ pollMs: 0, run: async a => a.includes("create") ? { stdout: JSON.stringify({ id: "x" }) } : { stdout: out } }); await assert.rejects(e.execute(wp, { workspace: { path: "/missing", baseSha: "a".repeat(40), branch: "b" } }), x => x.code === code && x.classification === cls && x.retryable === retry); });
test("Hermes command failure is retryable external", async () => { const e = new HermesAgentExecutor({ run: async () => { const x = Error("down"); x.code = "EPIPE"; throw x; } }); await assert.rejects(e.execute(wp, { workspace: { path: "/exact" } }), x => x.code === "HERMES_COMMAND_FAILED" && x.classification === "EXTERNAL_BLOCK" && x.retryable); });
